"""empty message

Revision ID: 57d02230e07f
Revises: 4821a61f13fd
Create Date: 2024-06-08 01:11:51.623412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d02230e07f'
down_revision = '4821a61f13fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint('person_favorites_fkey', type_='foreignkey')
        batch_op.drop_column('favorites')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('person_favorites_fkey', 'favorite_people', ['favorites'], ['id'])

    # ### end Alembic commands ###
