"""empty message

Revision ID: 85942c087556
Revises: 2421ff810b74
Create Date: 2024-06-06 00:05:55.697706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85942c087556'
down_revision = '2421ff810b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('mass', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('mass')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
